### PR TITLE
Add support for setting DelaySeconds for a Message

### PR DESCRIPTION
**Pull request by bjornpost**
See #34

### CODE REVIEW

**Comment by bjornpost** [comment]
Not sure on how to fix the broken tests. Directions welcome :-).

**Comment by h-bragg** [comment]
Within the file `SqsAdapterTest.php` `testEnqueue` method it expects some calls to `metadata-get` with MessageAttributes.

This method should also include mocks for calls to 'DelaySeconds'.

```php
$this->messageA->shouldRecieve('getMetadata->get')->once()->with('DelaySeconds')->andReturn(0);
```

and the `sendMessageBatch` method should have entries for the DelaySeconds property:

```php
['Id' => 0, 'MessageBody' => 'foo', 'MessageAttributes' => [], 'DelaySeconds' => 0],
```


Also there should be tests to ensure the DelaySettings functionally is actually working.

1. If DelaySeconds is set in the message metadata we expect to see if being passed to `sendMessageBatch`

We will also need to consider what the default behaviour here should be and write some specific tests for those.

1. If DelaySeconds is set in the options and not set on a Message what is the expected behaviour? _DelaySeconds should either not be there or should be the same as the options setting_
1. If DelaySeconds is not set at all and not set in options? _Either delay seconds should not be passed to the `sendMessageBatch` method or be set to 0._

Does that make sense?

If you would like me to write some of these tests let me know.

**Comment by bjornpost** [comment]
@h-bragg Spend a good hour or so trying to fix these tests, but Mockery keeps throwing exceptions at me which do not make a lot of sense to me. If you would like to add the tests: go for it. :-)

**Comment by h-bragg** [comment]
@bjornpost I created a new branch (and PR) #36 which the tests.

The tricky mockery exceptions are due to it not showing all of the differences between expected and actual arguments for method calls it is expecting.

**Comment by bjornpost** [comment]
Closing this in favor of #36

**Pull request closed without merging**
